baseurl = "https://www.eclipse.org/research"
DefaultContentLanguage = "en"
title = "Research @ Eclipse Foundation"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "Business-friendly open source and open innovation underpins exploitation, community building and dissemination strategy for European projects."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse", "research"]
  styles = "css/styles.css"
  gcse = "011805775785170369411:p3ec0igo0qq"
  js = "js/solstice.js"
# logo = ""
# favicon = ""
# share_img = ""
# header_wrapper_class = ""
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
# twitter_url = ""
  
[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  
[[menu.main]]
    name = "Members"
    url = "https://www.eclipse.org/membership/"
    weight = 1
    
[[menu.main]]
    name = "Working Groups"
    url = "https://www.eclipse.org/org/workinggroups/"
    weight = 2
    
[[menu.main]]
    name = "Projects"
    url = "https://www.eclipse.org/projects/"
    weight = 3